version: '3'
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0-beta.3
    ports:
    - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:dalong@pgspider-cstore:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  pgspider-pg_cron:
    image: dalongrong/pgspider:pg_cron
    volumes: 
    - "./.pgpass:/var/lib/postgresql/.pgpass"
    ports: 
    - "5432:5432"
    environment: 
    - "POSTGRES_PASSWORD=dalong"
  pgspider-cstore:
    image: dalongrong/pgspider:cstore
    ports: 
    - "5433:5432"
    environment: 
    - "POSTGRES_PASSWORD=dalong"